# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_comment_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='header',
            field=models.CharField(max_length=200),
        ),
    ]
