# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_categorymenu_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюдо'},
        ),
    ]
