# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20170715_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_like',
            field=models.CharField(max_length=5),
        ),
    ]
