# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_auto_20170715_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
